# Generated by Django 3.2.18 on 2023-05-01 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('allowed', models.ManyToManyField(related_name='allowed', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requested', models.ManyToManyField(related_name='requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
