# Generated by Django 4.2 on 2023-05-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_circle_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='owner',
            new_name='user',
        ),
    ]
