# Generated by Django 3.2.18 on 2023-05-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='content',
        ),
    ]
